app/controllers/think_feel_do_dashboard/coach_assignments_controller.rb
app/views/think_feel_do_dashboard/coach_assignments/_form.html.erb
app/views/think_feel_do_dashboard/coach_assignments/edit.html.erb
app/views/think_feel_do_dashboard/coach_assignments/new.html.erb
app/views/think_feel_do_dashboard/coach_assignments/show.html.erb
app/views/think_feel_do_dashboard/groups/_form.html.erb
app/views/think_feel_do_dashboard/groups/show.html.erb
app/views/think_feel_do_dashboard/participants/show.html.erb
spec/features/researchers/coach_assignments_spec.rb
spec/features/researchers/groups_spec.rb

Jah coach language

---

app/controllers/think_feel_do_dashboard/coach_assignments_controller.rb
spec/features/researchers/coach_assignments_spec.rb

* WOZ assignment now handles all social coach assignment
[#87751938]

Generalize coach assignment flash messages

---

config/locales/en.yml
spec/features/researchers/participants_spec.rb

* Fixed validation message for study id of participant.
[Finished #89144886]

Fixed validation error message.

---

app/views/think_feel_do_dashboard/groups/show.html.erb
spec/features/clinician/groups_spec.rb
spec/features/super_users/groups_spec.rb

* Added button to group page.
* Added checks for button in specs.
[#81643562]

Add group dash button.

---

app/views/think_feel_do_dashboard/memberships/_dates.html.erb
spec/features/researchers/coach_assignments_spec.rb

* Fixed an issue with an unnecessary month offset.
* Added a spec to ensure that a date was placed on page.
[#89231752]

Fix group assignment start date.

---

Gemfile
Gemfile.lock
spec/features/researchers/coach_assignments_spec.rb
spec/js_helper.rb

* Added phantonjs driver.
* Added js spec to check projected end date.
[Finished #89231752]

Add spec for projected end date.

---

app/models/think_feel_do_dashboard/reports/goal.rb
app/models/think_feel_do_dashboard/reports/like.rb

* Add new field to goal report.
* Add new field to like report.
[#86571058]

Add fields to reports.

---

app/views/think_feel_do_dashboard/groups/show.html.erb

* Added a check to ensure arm is social.
[#90111634]

Remove group dash button of non-social arms.

---

app/views/think_feel_do_dashboard/groups/show.html.erb

* Previously only moved location of button.
[Finished #90111634]

Remove button for non-social.

---

app/views/think_feel_do_dashboard/reports/index.html.erb

* Disclaimer now notes nightly creation.
[Finished #90633568]

Update reports disclaimer.

---

app/views/think_feel_do_dashboard/memberships/_form.html.erb

* Updated the membership form to use group_id rather than params[:id].
[Finished #91010606]

Fix membership form bug.

---

app/helpers/think_feel_do_dashboard/memberships_helper.rb
app/views/think_feel_do_dashboard/memberships/_dates.html.erb
config/locales/en.yml
spec/features/researchers/coach_assignments_spec.rb
spec/helpers/think_feel_do_dashboard/memberships_helper_spec.rb

* Removed Javascript calculation for end date.
* Now calculating end date via helper.
* Added spec for helper.
* Updated feature spec for membership creation.
[Finished #91623394]

Make projected end date more accurate.

---

Gemfile
Gemfile.lock
app/assets/javascripts/think_feel_do_dashboard.js
app/assets/javascripts/think_feel_do_dashboard/participants/_form.js
app/controllers/think_feel_do_dashboard/participants_controller.rb
app/views/think_feel_do_dashboard/participants/_form.html.erb
spec/dummy/app/assets/javascripts/application.js
spec/features/researchers/participants_spec.rb
spec/rails_helper.rb

* generate a random passphrase of simple words
[#91405400]

allow Researcher to set password for Participant

---

app/views/think_feel_do_dashboard/memberships/show.html.erb
config/locales/en.yml
spec/features/researchers/memberships_spec.rb

* Update date and time formats
* Update specs to expect new formats.
[#91544146]

Standardize date and datetimes

---

app/controllers/think_feel_do_dashboard/arms_controller.rb
app/views/think_feel_do_dashboard/arms/_form.html.erb
app/views/think_feel_do_dashboard/arms/show.html.erb
spec/dummy/app/models/arm.rb
spec/dummy/db/migrate/20150410174157_add_can_message_after_membership_complete_to_arms.rb
spec/dummy/db/migrate/20150410175659_populate_arm_message_flag.rb
spec/dummy/db/schema.rb

* Added new flag toggle to arm pages.
* Updated arm controller to expect new field.
[#91448610]

Add after-membership-complete messaging flag to arm modifications.

---

app/views/think_feel_do_dashboard/arms/_form.html.erb
app/views/think_feel_do_dashboard/arms/show.html.erb
spec/dummy/app/models/arm.rb
spec/features/super_users/arms_spec.rb

* Slight refactor of arm usage.
[#91448610]

Arm messaging flag

---

app/controllers/think_feel_do_dashboard/arms_controller.rb
spec/features/super_users/arms_spec.rb

* Updated controller logic for arm destruction.
* Added notice explaining arm deletion privileges.
* Added spec to ensure notice displays.
[Finished #92837924]

Remove ability to delete Arm.

---

app/controllers/think_feel_do_dashboard/memberships_controller.rb

remove validation that is handled at model level

---

app/models/think_feel_do_dashboard/concerns/group.rb
spec/features/clinician/profile_questions_spec.rb
spec/features/researchers/groups_spec.rb
spec/features/researchers/participants_spec.rb
spec/features/super_users/arms_spec.rb
spec/rails_helper.rb

* Change how moderating participant password is created to include a capitalized letter
* Remove space inside string interpolation
[#98987112]

Update AutoGenerated Password

---

app/models/think_feel_do_dashboard/concerns/group.rb

* Change base for a less likely change to have a password with 3 repeating values
[Finished: #98987112]

Change base 16 to base 64

---

app/views/think_feel_do_dashboard/participants/show.html.erb
spec/views/think_feel_do_dashboard/participants/show.html.erb_spec.rb

* Augment flash message for participant deletion
* Add view spec
[Finished: #110256638]

Improve Flash Message

---

app/views/think_feel_do_dashboard/arms/_form.html.erb
spec/features/super_users/arms_spec.rb
spec/views/think_feel_do_dashboard/arms/_form.html.erb_spec.rb

* Update text to be correct when creating or editing an arm
* Add spec
[Finished: #110288200]

Update Arm Form

---

app/controllers/think_feel_do_dashboard/application_controller.rb
app/helpers/think_feel_do_dashboard/application_helper.rb

* Move helpers into application helper file so they are loaded into host application

Expose Application Helpers

---

app/models/think_feel_do_dashboard/concerns/group.rb
spec/features/clinician/dashboard_links_spec.rb
spec/features/clinician/groups_spec.rb
spec/features/content_author/dashboard_links_spec.rb
spec/features/researchers/dashboard_links_spec.rb
spec/features/researchers/groups_spec.rb
spec/features/researchers/users_spec.rb
spec/features/super_users/dashboard_links_spec.rb
spec/features/super_users/groups_spec.rb
spec/features/super_users/users_spec.rb
spec/models/concerns/group_spec.rb

* Fix failing spec by adjusting password
* Remove some unnecessary code
[#111779364]

Fix Failing Spec

---

app/controllers/think_feel_do_dashboard/moderators_controller.rb
app/controllers/think_feel_do_dashboard/social_networking/profile_questions_controller.rb
spec/controllers/think_feel_do_dashboard/moderators_controller_spec.rb
spec/controllers/think_feel_do_dashboard/social_networking/profile_questions_controller_spec.rb
spec/dummy/db/schema.rb

* Add `authenticate_user!` to engine application folder
* Remvoe unnecessary `authentication_user!` form child controllers
[#113284567]

Add General Authentication

---

app/controllers/think_feel_do_dashboard/application_controller.rb
app/controllers/think_feel_do_dashboard/concerns/invalid_auth_token.rb
config/brakeman.ignore
spec/controllers/think_feel_do_dashboard/arms_controller_spec.rb
spec/support/controller_spec_helpers.rb

* Add rescue if token is invalid
* Add concern with rescue statement
* Include concern in controllers
* Add controller spec to test for authentication bug
[#113630033]

Rescue if Token is Invalid

---

app/controllers/think_feel_do_dashboard/memberships_controller.rb
spec/controllers/think_feel_do_dashboard/membership_controller_spec.rb
spec/dummy/config/environments/test.rb

* Updated show logic for membership controller.
* Added show specs for controller.
[#115812555]

Handling show requests when membership deleted.

---

app/controllers/think_feel_do_dashboard/arms_controller.rb
spec/controllers/think_feel_do_dashboard/arms_controller_spec.rb

* Added check for record not found.
* Updated controller to find Arms instead of using can can helper.
* Added specs for record not found and auth checks.
[#116466651]

Ems 116466651 - Update auth checks and add record not found handling.

---

app/controllers/think_feel_do_dashboard/groups_controller.rb
spec/controllers/think_feel_do_dashboard/groups_controllers_spec.rb

* Add rescue in group controller to handle restriction
* Update group specs
[#115522141]

Add Rescue to Display Error Message

---

.travis.yml
app/models/think_feel_do_dashboard/concerns/participant.rb
lib/think_feel_do_dashboard/version.rb

* cache gems
* test with Ruby 2.3.0

update Travis config

---

Gemfile
README.md
gemfiles/Gemfile.rails-5.0-beta
think_feel_do_dashboard.gemspec

* git_tagger gem
* repository moved from 'cbitstech' to 'NU-CBITS'

install internal gems; update repository URL

---

app/assets/javascripts/think_feel_do_dashboard/participants/_form.js

Update field generation logic to eliminate duplicate elements.

---

app/controllers/think_feel_do_dashboard/moderators_controller.rb
spec/controllers/think_feel_do_dashboard/moderators_controller_spec.rb

* Update controller logic to check for active memberships.
* Redirecting with alert message describing the problem.
* Added spec for the empty membership condition.
[#118867739]

Fix issue with mod participant login for empty group.

---

.gitignore
app/controllers/think_feel_do_dashboard/participants_controller.rb
spec/controllers/think_feel_do_dashboard/participants_controller_spec.rb

* Add `rescue` when participants aren't found
* Add controller spec
[Finishes: #121324611]

Add Rescue
